include(CMakeFindDependencyMacro)
find_dependency(uo_cb 0.1.0)
find_dependency(uo_err 0.1.0)
find_dependency(uo_mem 0.1.0)
find_dependency(uo_queue 0.1.0)
find_dependency(uo_sock 0.1.0)
if(WIN32)
    set(OPENSSL_ROOT_DIR "/Program files/OpenSSL")
endif()
find_dependency(OpenSSL)
include("${CMAKE_CURRENT_LIST_DIR}/uo_httpcTargets.cmake")